name: Pipeline
on: 
  push:
    paths: 
    - '.github/workflows/pipeline.yaml'
    - 'pipeline/lastrun.txt'
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
