name: Compiler
on: 
  push:
    paths:
    - '.github/workflows/compiler.yaml'
jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: gambuzzi/ga-compile-pipeline@main
        with:
          build: 'make build'
          publish: 'make publish'
             