name: Compiler
on: 
  push:
    paths-ignore:
    - 'pipeline/lastrun.txt'
    - '.github/workflows/pipeline.yaml'
    - '.github/workflows/pipeline.yml'
jobs:
  buildpipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Build the pipeline yaml file
        run: |
          cd pipeline
          date +%s > lastrun.txt
          date >> lastrun.txt
          cp pipeline.yaml ../.github/workflows/pipeline.yaml
          # make build
      - name: Commit pipeline
        run: |
          git config --global user.name 'Autobot'
          git config --global user.email 'no-reply@users.noreply.github.com'
          git add .github/workflows/pipeline.yaml
          git add pipeline/lastrun.txt
          git commit -m "Automated pipeline build"
          git push