name: Compiler
on: 
  push:
    paths-ignore:
      - .github/workflows/pipeline.yaml
      - .github/workflows/pipeline.yml
jobs:
  buildpipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Build the pipeline yaml file
        run: |
          echo <<EOF > .github/workflows/pipeline.yaml
          name: Pipeline
          on: push
          jobs:
            build-pipeline:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v2
          EOF
          date +%s > pipeline/lastrun.txt
          echo "" >> pipeline/lastrun.txt
          date >> pipeline/lastrun.txt
          cd pipeline
          # make build
      - name: Commit pipeline
        run: |
          git config --global user.name 'Autobot'
          git config --global user.email 'no-reply@users.noreply.github.com'
          git add -A
          git commit -m "Automated pipeline build"
          git push