name: Compiler
on: 
  push:
    paths:
    - '.github/workflows/compiler.yaml'
jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: actions/checkout@v1
        working-directory: ${{ github.workspace }}
        with:
          repository: gambuzzi/ga-compile-pipeline
          ref: main
          path: .github/actions/gambuzzi/ga-compile-pipeline
      - uses: gambuzzi/ga-compile-pipeline@main
        with:
          build: 'make build'
          publish: 'make publish'
             