name: Pipeline
on:
  push:
    paths-ignore:
      - .github/workflows/compiler.yaml
env:
  PROGRAM: pipiline_test
  REGISTRY: docker.io/user
  IMG_NAME: pipiline_test
  MAINTAINER: gambuzzi
  OWNER: gambuzzi
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Env Setup
        run: >
          echo "::set-env name=COMMIT::$(shell git rev-parse HEAD)"

          echo "::set-env name=PYMD5::$(shell find . \( -name '*.py' -o -name '*.sh' \) -exec cat {} + | md5)"
      - name: Env Setup 2
        run: |
          echo "::set-env name=TAG::$(COMMIT)-$(PYMD5)"
      - name: Env Setup 3
        run: |
          echo "::set-env name=IMG::$(REGISTRY)/$(PROGRAM):$(TAG)"
      - name: Build
        run: |
          docker build --target=production -t ${IMG_NAME} .
      - name: Build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker tag ${IMG_NAME} ${IMG}
          docker push ${IMG}
# Sat Jan 30 17:05:48 UTC 2021
