name: Pipeline
on:
  push:
    paths-ignore:
      - .github/workflows/compiler.yaml
env:
  PROGRAM: tests
  REGISTRY: gambuzzi
  IMG_NAME: pipeline-test
  MAINTAINER: gambuzzi
  OWNER: gambuzzi
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Env Setup
        run: >
          echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

          echo "PYMD5=$(find . \( -name '*.py' -o -name '*.sh' \) -exec cat {} + | md5sum | awk '{print $1}')" >> $GITHUB_ENV
      - name: Env Setup 2
        run: |
          echo "TAG=${{ env.COMMIT }}-${{ env.PYMD5 }}" >> $GITHUB_ENV
      - name: Env Setup 3
        run: >
          echo "IMG=${{ env.REGISTRY }}/${{ env.PROGRAM }}:${{ env.TAG }}" >>
          $GITHUB_ENV
      - name: Build
        run: |
          docker build -t ${IMG_NAME} .
      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "::add-mask::${DOCKER_PASSWORD}"
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker tag ${IMG_NAME} ${{ env.IMG }}
          docker push ${{ env.IMG }}
# Sat Jan 30 18:26:57 UTC 2021
