name: Pipeline
on: 
  push:
    paths-ignore:
    - '.github/workflows/compiler.yaml'  
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
# Fri Jan 29 16:37:27 UTC 2021
